version: '3'

services:
  api:
    build: .
    ports:
      - "4000:8888"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  db:
    image: "postgres:9.6"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

# volumes:
#   db-data: {}
